home_page: home.md
menu_page: menu.md
author_img: avatar.jpg
favicon_url: favicon.png

zoom_image: true
codeblock:
  highlight_theme: normal

comments:
  utterances:
    enable: false
  disqus:
    enable: false
  gitalk:
    enable: false
